# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20170510_0331'),
        ('general', '0006_auto_20170523_0027'),
    ]

    operations = [
    ]
