# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_merge_20170523_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='postal',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='fb_id',
            field=models.CharField(blank=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
