# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_auto_20170529_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='editors',
            field=models.ManyToManyField(related_name='editor_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
