# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_list_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='likes',
            field=models.ManyToManyField(related_name='like_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
