# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_list_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='likes',
        ),
        migrations.AddField(
            model_name='list',
            name='likers',
            field=models.ManyToManyField(related_name='liker_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
