# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
