# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20170529_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='has_pic',
            field=models.BooleanField(default=False),
        ),
    ]
