# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_notification_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='reset_key',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='profile_pic',
            field=models.TextField(blank=True),
        ),
    ]
