# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_auto_20170729_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='has_pic',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='reset_key',
            field=models.TextField(default='1'),
        ),
    ]
