# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_auto_20170729_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='profile_pic',
            field=models.TextField(blank=True),
        ),
    ]
