# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_siteuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='show_welcome',
            field=models.BooleanField(default=True),
        ),
    ]
